/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/desempenho` | `/desempenho`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/simulados` | `/simulados`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/desempenho` | `/desempenho`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/simulados` | `/simulados`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/desempenho${`?${string}` | `#${string}` | ''}` | `/desempenho${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias${`?${string}` | `#${string}` | ''}` | `/materias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/metas${`?${string}` | `#${string}` | ''}` | `/metas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/simulados${`?${string}` | `#${string}` | ''}` | `/simulados${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/desempenho` | `/desempenho`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/simulados` | `/simulados`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
